name: app lint

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      app: ${{ steps.changes.outputs.app }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check for file changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          token: ${{ github.token }}
          filters: .github/filter.yaml

  lint:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.app == 'true' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: cache cargo
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  app-lint-check:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ ! failure() }}
    steps:
      - name: check
        run: echo "app lint is successfully executed."
